[package]
name = "univ"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
tokio = { version = "1", features = ["full"] }
askama = "0.12"
actix-files = "0.6"
rand = "0.8"
dotenv = "0.15"